Implement editing project page
Huy-Ngo/acanban pull request #116
Opened 2021-01-05 15:17 UTC by Huy-Ngo

It is supposed to resolve #93

2021-01-05 15:19 UTC, McSinyx commented on src/acanban/templates/project-detail.html
> +  {{ tab('Info', '', true) }}
Probably you'll need a macro to pass in which tab is active.

2021-01-06 04:26 UTC, Huy-Ngo commented
I haven't written test yet.

2021-01-06 04:28 UTC, Huy-Ngo commented
Ah the redirect one is resulting in the problem

2021-01-06 04:33 UTC, McSinyx commented on src/acanban/project.py
> +            project = await project.pluck(*BASIC_FIELDS).run(connection)
Ah I remember now, probject is *project object* LOL.

2021-01-06 10:15 UTC, Huy-Ngo commented
This is for testing the redirect

2021-01-06 10:46 UTC, Huy-Ngo commented
I hope it pass now :pray:

2021-01-06 11:03 UTC, McSinyx commented
Nice factoring, I'm excited!  BTW it's 2021 now.

2021-01-06 12:31 UTC, Huy-Ngo commented
On Wed, Jan 6, 2021 at 6:03 PM Nguyễn Gia Phong
<notifications@github.com> wrote:
>
> BTW it's 2021 now.

Thanks. Rookie mistake, lol

2021-01-06 12:45 UTC, Huy-Ngo commented
Yay test passsed!

2021-01-06 13:27 UTC, McSinyx requested changes

2021-01-06 13:27 UTC, McSinyx commented on src/acanban/templates/project-edit.html
> +    </textarea>
The thing in value should be the tag's content instead.

2021-01-06 13:27 UTC, McSinyx commented on src/acanban/templates/project-edit.html
> +           value={{ project.name }} required/>
The value needs quoting.

2021-01-06 13:27 UTC, McSinyx commented on src/acanban/templates/project-detail.html
> +{% if endpoint is none %}{% set endpoint = name|lower %}{% endif %}
We can drop the condition here now.

2021-01-06 13:27 UTC, McSinyx commented on src/acanban/project.py
> +@blueprint.route('/<uuid>')
IDK the reason behind this, but FYI with this  `/p/<uuid>/` is giving me Not Found.

2021-01-07 02:13 UTC, Huy-Ngo commented on src/acanban/project.py
> +@blueprint.route('/<uuid>')
Because other links are to `/uuid` and not `/uuid//`

2021-01-07 02:15 UTC, Huy-Ngo commented on src/acanban/project.py
> +@blueprint.route('/<uuid>')
For example, in `myproject.html`:

```jinja
   <h2><a href=/p/{{ project.id }}><b>Title:</b> {{ project.name }}</a></h2>
```

2021-01-07 02:19 UTC, Huy-Ngo commented on src/acanban/templates/project-edit.html
> +    </textarea>
Wait I thought I did that already.

2021-01-07 02:21 UTC, Huy-Ngo commented on src/acanban/templates/project-edit.html
> +           value={{ project.name }} required/>
I was sure I did this too. Maybe I didn't commit or smt.

2021-01-07 03:01 UTC, McSinyx commented on src/acanban/project.py
> +@blueprint.route('/<uuid>')
Quart (?) redirects `/foobar/` to `/foobar`, but not the other way around.

2021-01-07 03:02 UTC, McSinyx commented on src/acanban/templates/project-detail.html
> +{% if endpoint is none %}{% set endpoint = name|lower %}{% endif %}
With the conditional removed, we no longer need to pass the endpoint as argument since it's to be overridden anyway.

2021-01-07 03:25 UTC, Huy-Ngo commented on src/acanban/project.py
> +@blueprint.route('/<uuid>')
Well, I guess I should edit the test then, because otherwise the coverage doesn't count that.

2021-01-07 12:46 UTC, Huy-Ngo commented
@McSinyx Any other requests?

2021-01-07 12:52 UTC, Huy-Ngo commented
Wait but but but.. it passed before the rebase

2021-01-07 13:01 UTC, Huy-Ngo commented
passed yay

2021-01-07 13:28 UTC, McSinyx approved these changes
> @McSinyx Any other requests?

Nope :upside_down_face:

2021-01-12 03:57 UTC, 9a24f0 commented on src/acanban/project.py
> +    return redirect(f'/p/{uuid}/info')
why is this needed? and I think this should be a void function which should returns nothing.

2021-01-12 03:57 UTC, 9a24f0 commented on src/acanban/project.py
> +            user_projects = await current_user.projects
is this what QuartAuth have or we define it?

2021-01-12 03:57 UTC, 9a24f0 commented on src/acanban/project.py
> +        await project_query.update(updated).run(conn)
Is `current_app` need to be update? I see you already did it 10 lines above:
```python
async with current_app.db_pool.connection() as connection:
```

2021-01-12 04:03 UTC, McSinyx commented on src/acanban/project.py
> +    return redirect(f'/p/{uuid}/info')
For UX I'd guess, e.g. when one manipulate the URL by hand perse only need to remove the last part and still get a page that works (so that navigation is two-way).

2021-01-12 04:04 UTC, McSinyx commented on src/acanban/project.py
> +            user_projects = await current_user.projects
It's from the RethinkObject mixin.

2021-01-12 04:21 UTC, 9a24f0 commented on src/acanban/project.py
> +    return redirect(f'/p/{uuid}/info')
So it's for later dev purpose?

2021-01-12 04:23 UTC, 9a24f0 commented on src/acanban/project.py
> +            user_projects = await current_user.projects
I thought I add comment for only line 78 :sweat_smile:  I'm wondering why he can use `current_user.<something>`

2021-01-12 04:23 UTC, McSinyx commented on src/acanban/project.py
> +    return redirect(f'/p/{uuid}/info')
No it's for current experience, e.g. like when you go from https://github.com/Huy-Ngo/acanban/pull to https://github.com/Huy-Ngo/acanban it's still the root project.

2021-01-12 04:27 UTC, McSinyx commented on src/acanban/project.py
> +            user_projects = await current_user.projects
current_user is a proxy to our User, which has the RethinkObject mixin defining the projects field: https://github.com/Huy-Ngo/acanban/blob/f2a9d5ee6d9c8c95545e994d4ea8731c6470db0b/src/acanban/auth.py#L63

Note that the mixin is only useful when you only need a very few number of fields from a row; otherwise constructing a pluck would be a lot more I/O friendly.

2021-01-12 04:38 UTC, McSinyx commented on src/acanban/project.py
> +        await project_query.update(updated).run(conn)
Thinking about it, L77-L81 should be move to the beginning of the function.  The same for `info`.

2021-01-12 09:38 UTC, Huy-Ngo commented on src/acanban/project.py
> +    return redirect(f'/p/{uuid}/info')
It's mostly for not having to edit all the current links to have `/info`.

2021-01-12 09:43 UTC, Huy-Ngo commented on src/acanban/project.py
> +        await project_query.update(updated).run(conn)
> L77-L81 should be move to the beginning of the function.

It's already at the beginning tho? Do ye mean I should not use two connections in the same function?

2021-01-12 09:43 UTC, Huy-Ngo commented on src/acanban/project.py
> +            user_projects = await current_user.projects
Thanks for explaining that.

2021-01-13 05:13 UTC, 9a24f0 approved these changes
LGTM!

2021-01-13 05:14 UTC, merged