Implement project creation
Huy-Ngo/acanban pull request #122
Opened 2021-01-11 05:46 UTC by 9a24f0

2021-01-11 06:01 UTC, 9a24f0 commented
Erm... why it's rename the commits as "resolve conflicts"

2021-01-11 08:39 UTC, Huy-Ngo commented
You need to write the stubs (see `stubs/`

2021-01-12 03:14 UTC, Huy-Ngo approved these changes
LGTM

2021-01-12 03:15 UTC, Huy-Ngo commented
Your turn to review mine? :stuck_out_tongue:

2021-01-12 04:21 UTC, McSinyx requested changes

2021-01-12 04:21 UTC, McSinyx commented on src/acanban/templates/project-create.html
> +  {% endif %}
This doesn't seem to be used.

2021-01-12 04:21 UTC, McSinyx commented on stubs/rethinkdb/__init__.pyi
> +    row: dict[str, Any]
Technically this is not correct since row does not have `__len__`.  Probably hinting it as ImplicitVar with `__getitem__` returning Any would be good enough.  Ideally it should be explicitly hinted (so is the table method below) but our unit tests would cover it so it's probably OK.

2021-01-12 04:21 UTC, McSinyx commented on tests/test_project.py
> +    """Test successful and failed create project."""
Why are all docstrings the same?

2021-01-12 04:25 UTC, 9a24f0 commented on src/acanban/templates/project-create.html
> +  {% endif %}
Do we have any error in project create? :confused: If not I'll go remove these.

2021-01-12 04:29 UTC, 9a24f0 commented on tests/test_project.py
> +    """Test successful and failed create project."""
Addressed at 4c0e6e2fa2dd72d3f2e55bcbfb0a1b1b71e36670

2021-01-12 04:30 UTC, 9a24f0 commented on stubs/rethinkdb/__init__.pyi
> +    row: dict[str, Any]
Test passed so I'll accept it as good :smile:

2021-01-12 04:32 UTC, McSinyx commented on stubs/rethinkdb/__init__.pyi
> +    row: dict[str, Any]
Nope it's false positive.

2021-01-12 04:32 UTC, McSinyx commented on src/acanban/templates/project-create.html
> +  {% endif %}
Looking at your current code I don't see any point where there would be an error.

2021-01-12 04:41 UTC, 9a24f0 commented on src/acanban/templates/project-create.html
> +  {% endif %}
Let's remove these and see if user could test out errors :smile:

2021-01-13 06:58 UTC, McSinyx approved these changes
You need to resolve the conflict tho.

2021-01-13 13:00 UTC, Huy-Ngo commented
This should go without saying but be careful not to remove my parts and squash commits instead of rebase.

2021-01-14 02:39 UTC, merged