Add member tab and add member invitation
Huy-Ngo/acanban pull request #124
Opened 2021-01-13 14:30 UTC by Huy-Ngo

Draft for now, since I intend to resolve #117 

I'm not sure if I should delete the member list from info so I kept it as a separate commit till I hear your opinion.

Should we put an invitation notification at home page?

2021-01-14 13:28 UTC, Huy-Ngo commented on src/acanban/project.py
> +        # FIX ME: checking student and supervisors not working
The check is in the `if` block 9 lines below but ok

2021-01-16 05:08 UTC, Huy-Ngo commented
Please pull rebase from main, so that the stubs are included

Current lint fail is:

```
src/acanban/project.py:136: error: "RethinkDB" has no attribute "row"
src/acanban/project.py:141: error: "RethinkDB" has no attribute "row"
```

2021-01-21 04:30 UTC, McSinyx requested changes

2021-01-21 04:30 UTC, McSinyx commented on src/acanban/project.py
> +    return redirect(f'/p/{uuid}/members')
The conditionals here are hard to follow.  If you want to deliver a message *and* short-circuit the execution, use an exception instead of the flash-return pair.  Plus some exceptions give you different status code, which makes testing easier.

2021-01-21 04:30 UTC, McSinyx commented on src/acanban/project.py
> +            raise Unauthorized
Use `pluck` defined above.

2021-01-21 04:30 UTC, McSinyx commented on src/acanban/project.py
> +            raise Unauthorized
Use `pluck` defined above.

2021-01-21 04:30 UTC, McSinyx commented on src/acanban/templates/project-info.html
> -                         | join(', ') | safe }}</p>
With this removed, make sure you edit BASIC_FIELDS to not contain information not used by `info` and `edit`.

2021-01-21 18:47 UTC, 9a24f0 commented on src/acanban/project.py
> +            raise Unauthorized
Addressed at 537fac5e0fb1b5044d0e36abe68b456fcccfa562

2021-01-21 18:48 UTC, 9a24f0 commented on src/acanban/project.py
> +            raise Unauthorized
Addressed at 537fac5e0fb1b5044d0e36abe68b456fcccfa562

2021-01-21 18:53 UTC, McSinyx commented on src/acanban/project.py
> +    new_name = form['new-user']
LOL

2021-01-21 18:53 UTC, McSinyx commented on src/acanban/project.py
> +        user = await r.table('users').get(new_name).run(conn)
To minimize the I/O, you might want to `.pluck()` here.

2021-01-21 18:57 UTC, McSinyx commented on src/acanban/project.py
> +    return redirect(f'/p/{uuid}/members')
This is still hard to follow.  Once again I suggest short-circuiting to unnest the conditionals.  Exceptions doesn't seem to be the right thing to do here, so probably try to return the rendered page with the error directly.  That will give you 200 on user input error, 302 on success (btw there's `request.referrer`) and 4xx on other user errors.

2021-01-23 09:03 UTC, McSinyx commented on src/acanban/project.py
> +        user = await r.table('users').get(new_name).run(conn)
My mistake, `user['projects']` is used below.

2021-01-23 10:16 UTC, McSinyx approved these changes
The tests better be more assertive, but from the higher-level view the implementation is fine I guess.

2021-01-24 09:24 UTC, Huy-Ngo commented
You can add tests later (make an issue for reminder if necessary).
I think all existing tests are quite lousy anyway.

2021-01-24 09:24 UTC, merged