Security Document
Huy-Ngo/acanban pull request #19
Opened 2020-11-17 01:01 UTC by Yus147

2020-11-17 03:01 UTC, McSinyx requested changes
CDN is cool, any idea how to use it?  As for load balancer, please see previous discussions (I'm too tired to look them up right now).  Firewall seems like a bright idea too.  ACL are already implemented in our persistency nodes IIUC though.  You'd need to look into Gatekeeper and provide a TL;DR on what it does and how to use it too.

Also what are other possible attacks?  In other words, you're doing this too late and too little to provide understanding to other team members.  Please try to submit as early as you can next time to make time for review and discussion.

2020-11-17 03:01 UTC, McSinyx commented on docs/source/Security/Security.rst
> +https://rethinkdb.com/docs/security/
Please elaborate on this.

2020-11-18 09:00 UTC, Huy-Ngo commented
Please elaborate more. DDoS is not the only security vulnerability.

2020-11-18 12:26 UTC, DDHLong commented
@Yus147 nitpick: branch name should be in lowercase

2020-11-21 08:06 UTC, McSinyx commented
@Yus147, I highly recommend you put some effort reworking this.

2020-12-14 15:13 UTC, McSinyx commented
Most DoS mitigation measures are carried out by either [Hypercorn](https://pgjones.gitlab.io/hypercorn/discussion/dos_mitigations.html) or [Quart](https://pgjones.gitlab.io/quart/discussion/dos_mitigations.html), except for data dribble (yes, a simple curl shows acanban.ga is over HTTP/2).  Other parts are addressed via configurations so I guess it is safe to close this and its linked issue for now.

2020-12-14 15:13 UTC, closed without merging