[Doc] Add difficulties to discussion
Huy-Ngo/acanban pull request #199
Opened 2021-01-30 13:44 UTC by Huy-Ngo

I add the difficulties in doing the group project to the discussion.
If you find yourselves to have some other difficulties feel free to add.

2021-01-30 13:50 UTC, Huy-Ngo commented
Should I delete the screenshot themselves too?

2021-01-30 18:04 UTC, 9a24f0 requested changes
I'm good with the difficulties, you should also remove the screenshots too.

2021-01-30 18:04 UTC, 9a24f0 commented on docs/source/result.rst
> +some members' expectations of the project and workflows.  People tended to work
Double space here

2021-01-30 18:04 UTC, 9a24f0 commented on docs/source/result.rst
> +with web development in Python, let alone the framework.  This revealed another
Here too

2021-01-31 03:10 UTC, 9a24f0 approved these changes
LGTM!

2021-01-31 03:11 UTC, merged