Make the host and port as command line argument
Huy-Ngo/acanban pull request #28
Opened 2020-11-21 09:26 UTC by Huy-Ngo

2020-11-21 13:30 UTC, McSinyx requested changes

2020-11-21 13:30 UTC, McSinyx commented on acanban/__main__.py
> +    parser = ArgumentParser('Additional configuration for the server.')
The following, or [something that produces `python -m acanban`](https://git.sr.ht/~cnx/offre/tree/a01a3874d74581a085c27492c121c66dd2e5554f/offre/__main__.py#L33).

```suggestion
    parser = ArgumentParser(prog='acanban')
```

2020-11-21 13:30 UTC, McSinyx commented on acanban/__main__.py
> +    config.bind = [f'{parser.host}:{parser.port}']
parse_args returns, well, the parsed args, hence the CI failure.  Also I suggest mirroring Hypercorn's option (see `hypercorn -h`) and use the address instead of splitting it to host and port, since it'd be less cumbersome to bind to multiple addresses.

2020-11-22 04:29 UTC, McSinyx requested changes
Some minor nits.

2020-11-22 04:29 UTC, McSinyx commented on acanban/__main__.py
> +from argparse import ArgumentParser
```suggestion

from argparse import ArgumentParser
```

2020-11-22 04:29 UTC, McSinyx commented on acanban/__main__.py
> +    config.bind = [f'{args.bind}']
```suggestion
    config.bind = [args.bind]
```

2020-11-22 09:08 UTC, Huy-Ngo commented on acanban/__main__.py
> +    config.bind = [f'{args.bind}']
🤦‍♂️

2020-11-22 09:09 UTC, McSinyx approved these changes

2020-11-22 15:15 UTC, 9a24f0 approved these changes
I trust @McSinyx on this 😁

2020-11-22 15:19 UTC, McSinyx commented
@Huy-Ngo, squash and merge if you're in a hurry to get it working on our test server, otherwise I'll come with another patch using config file for the ease of testing.

2020-11-23 02:35 UTC, merged