Implement user profile endpoint
Huy-Ngo/acanban pull request #72
Opened 2020-12-17 14:15 UTC by Huy-Ngo

Resolve #67 

In this project, I implement endpoints `/u/<username>` and `/u/<username>/edit`.

I also edit the title to be a block so that it can be extended in children templates.

This is not done yet: I haven't check if the signed in user is the user that can edit a profile.

2020-12-20 13:12 UTC, McSinyx commented
Gentle ping!

2020-12-21 03:53 UTC, Huy-Ngo commented
Yay green

2020-12-21 03:56 UTC, McSinyx commented
Maybe a rebase on top of `main` first?

2020-12-21 06:34 UTC, Huy-Ngo commented
Yey it's green again.

2020-12-21 09:08 UTC, McSinyx requested changes

2020-12-21 09:08 UTC, McSinyx commented on src/acanban/user.py
> +    return await render_template('user_profile.html', user=user)
```suggestion
    try:
        return await render_template('user_profile.html', user=User(username))
    except ReqlNonExistenceError:
        abort(HTTPStatus.NOT_FOUND)

2020-12-21 09:08 UTC, McSinyx commented on src/acanban/user.py
> +        return await render_template('user_profile_edit.html', user=user)
Same here.

2020-12-21 09:08 UTC, McSinyx commented on src/acanban/user.py
> +        abort(HTTPStatus.BAD_REQUEST)
When does this happen?  Could you handle it in `/register` as well?

2020-12-21 09:08 UTC, McSinyx commented on src/acanban/user.py
> +    await user.update(name=name, email=email)
This looks like a lot of unnecessary I/O.

2020-12-21 09:08 UTC, McSinyx commented on tests/test_user.py
> +        '/login', form=dict(username='silasl', password='lsalis'))
Please make this a fixture (probably in conftest even, most tests are for logged sessions)..

2020-12-21 12:20 UTC, Huy-Ngo commented on src/acanban/templates/user_profile_edit.html
> +<h3> u/{{ user.key }} </h3>
What do you mean?

2020-12-21 12:20 UTC, Huy-Ngo commented on src/acanban/templates/user_profile_edit.html
> +    value="{{ user.name }}" placeholder="Full name"/>
Oh right I already put the labels.

2020-12-21 12:21 UTC, Huy-Ngo commented on src/acanban/user.py
> +# Authentication handler
Oof

2020-12-21 12:22 UTC, Huy-Ngo commented on src/acanban/user.py
> +        abort(HTTPStatus.BAD_REQUEST)
When someone manually sends request without name or email key (see the last test).

2020-12-21 12:35 UTC, Huy-Ngo commented on src/acanban/templates/user_profile.html
> +  <button>Edit profile</button>
I thought the style should be already there.

2020-12-21 12:45 UTC, Huy-Ngo commented on src/acanban/user.py
> +        abort(HTTPStatus.BAD_REQUEST)
>  Could you handle it in `/register` as well?

Well probably in another PR.

2020-12-21 12:48 UTC, Huy-Ngo commented on src/acanban/user.py
> +    await user.update(name=name, email=email)
This is to avoid making someone's name empty. Maybe this is better in terms of IO:

```python
    if name != '' and email != '':
        await user.update(name=name, email=email)
    elif email == '':
        await user.update(name=name)
    elif name == '':
        await user.update(email=email)
```

2020-12-21 12:59 UTC, Huy-Ngo commented on tests/test_user.py
> +        '/login', form=dict(username='silasl', password='lsalis'))
I'll create 3 fixtures for 3 roles.

2020-12-21 13:02 UTC, Huy-Ngo commented on src/acanban/user.py
> +    await user.update(name=name, email=email)
The number of branches would escalate quickly when there are more details, though, so you'd like to reconsider that.

2020-12-21 13:07 UTC, Huy-Ngo commented on src/acanban/templates/user_profile.html
> +<h3> u/{{ user.key }} </h3>
I'd prefer `div` since it's not a paragraph but I'll change it later.

2020-12-21 13:07 UTC, Huy-Ngo commented on src/acanban/templates/user_profile.html
> +  <button>Edit profile</button>
I thought it's already styled.

2020-12-21 13:30 UTC, McSinyx commented on src/acanban/templates/user_profile.html
> +  <button>Edit profile</button>
Sorry, didn't thought that it would be used.  You can use `input[type=submit]` if you really don't want to do it, but I *think* putting `button` next to the `input` equivalent in the stylesheet should do.

2020-12-21 13:31 UTC, McSinyx commented on src/acanban/templates/user_profile_edit.html
> +<h3> u/{{ user.key }} </h3>
It's an edit page, but one's not suppose to edit per role nor username, so it might make sense to use readonly `input`.  `p` is cool too.

2020-12-21 13:32 UTC, McSinyx commented on src/acanban/templates/user_profile.html
> +<p> u/{{ user.key }} </p>
```suggestion
<h1>{{ user.name }}</h1>
<p>{{ user.role }}</p>
<p>u/{{ user.key }}</p>
```

2020-12-21 13:33 UTC, McSinyx commented on src/acanban/user.py
> +        abort(HTTPStatus.BAD_REQUEST)
SGTM.

2020-12-21 13:34 UTC, McSinyx commented on src/acanban/user.py
> +    await user.update(name=name, email=email)
You can always iterate on `info` (with extra care on unexpected fields).

2020-12-21 13:41 UTC, McSinyx commented on src/acanban/user.py
> +        return await render_template('user_profile_edit.html', user=user)
The exception is only raised by the second `if` so I think currently the `try` scope is a bit too broad.

2020-12-21 14:10 UTC, Huy-Ngo commented on src/acanban/user.py
> +    await user.update(name=name, email=email)
Not all fields need this. E.g. bio can be empty.

2020-12-21 14:11 UTC, Huy-Ngo commented on src/acanban/templates/user_profile.html
> +  <button>Edit profile</button>
Maybe make it a `button.submit` and add it along with `input[type=submit]`?

2020-12-21 14:12 UTC, McSinyx commented on src/acanban/user.py
> +    await user.update(name=name, email=email)
Then you can make use of a mapping, then `**` it into `user.update`.

2020-12-21 14:13 UTC, McSinyx commented on src/acanban/templates/user_profile.html
> +  <button>Edit profile</button>
Even just `button` would do, all buttons should look the same except for the color (source: dude trust me I spent my teenage years theming).

2020-12-21 14:19 UTC, Huy-Ngo commented on src/acanban/user.py
> +        return await render_template('user_profile_edit.html', user=user)
Yea, and it also leads to the current failing tests

2020-12-22 02:56 UTC, Huy-Ngo commented on src/acanban/user.py
> +        return await render_template('user_profile_edit.html', user=user)
Hmm on second thought I'd just remove the not found here lol

2020-12-22 03:46 UTC, McSinyx commented on src/acanban/templates/user_profile.html
> +<p> u/{{ user.key }} </p>
FYI you're still creating trailing whitespaces in the rendered page.

2020-12-22 03:48 UTC, McSinyx commented on src/acanban/user.py
> +    await user.update(name=name, email=email)
On third thought we should provide better feedback than implicitly falling back to the previous value, e.g. via an error banner.  Same for valid inputs: a S U C C banner should be there.

2020-12-25 13:07 UTC, Huy-Ngo commented on src/acanban/templates/user_profile.html
> +<p> u/{{ user.key }} </p>
Does it matter, though? No one is gonna read it.

2020-12-25 13:26 UTC, McSinyx commented on src/acanban/templates/user_profile.html
> +<p> u/{{ user.key }} </p>
What do you mean by no one?

2020-12-25 13:27 UTC, Huy-Ngo commented on src/acanban/user.py
> +    await user.update(name=name, email=email)
I think that kind of form validation should be on the frontend side (i.e. if the field is empty, there's a warning/error message displayed), and on backend side we still have to do this to protect the data from manual requests. Also, I don't know how to display banners that users can dismiss without using JS.

2020-12-25 13:39 UTC, McSinyx commented on src/acanban/user.py
> +    await user.update(name=name, email=email)
What I meant was on success you return the same page with a success banner (since it's an update operation); otherwise still the same page with an error banner.  The user needs not to dismiss an error, but rather either abort (close tab) or enter the valid input.  That's the general idea for the general case.

In certain occasions (e.g. this one) you can use `pattern` or `requires` to let the browser perform some primitive checking, but that does not prevent one from hand crafting malicious requests and mess up the DB, so we still need to do something in the backend.  Throwing errors instead of silently swallowing them is just my personal preference, for a reason that raising exception is the less cumbersome control flow.

2020-12-25 13:54 UTC, Huy-Ngo commented on src/acanban/user.py
> +    await user.update(name=name, email=email)
I kinda expect to be redirected to the view page rather than the edit page if success.

2020-12-25 13:55 UTC, McSinyx commented on src/acanban/user.py
> +    await user.update(name=name, email=email)
That sounds good too.

2020-12-25 13:56 UTC, Huy-Ngo commented on src/acanban/templates/user_profile.html
> +<p> u/{{ user.key }} </p>
I mean how many users are gonna check the source HTML, and how many of them care that there are some trailing whitespaces?

2020-12-25 13:57 UTC, McSinyx commented on src/acanban/templates/user_profile.html
> +<p> u/{{ user.key }} </p>
Not the source, the actual rendered page.

2020-12-25 14:20 UTC, Huy-Ngo commented on src/acanban/templates/user_profile.html
> +<p> u/{{ user.key }} </p>
OK fixed now I guess.

2020-12-25 14:21 UTC, Huy-Ngo commented on src/acanban/user.py
> +    await user.update(name=name, email=email)
Do you still need the banner?

2020-12-25 14:27 UTC, McSinyx commented on src/acanban/user.py
> +    await user.update(name=name, email=email)
Probably not, but you need to test the pages yourself to see if the UX is OK.

2020-12-28 04:03 UTC, Huy-Ngo commented
@McSinyx Do you have other change request?

2020-12-28 04:12 UTC, McSinyx commented
Nope, resolve my older request of making it look something different from this:
![2020-12-28T11:11:49](https://user-images.githubusercontent.com/13689192/103189046-8332c380-48fd-11eb-9902-1e0bf9023fa3.png)

2020-12-28 10:56 UTC, Huy-Ngo commented
On Mon, 28 Dec 2020, 11:12 Nguyễn Gia Phong, <notifications@github.com>
wrote:

> Nope, resolve my older request of making it look something different from
> this:
> [image: 2020-12-28T11:11:49]
> <https://user-images.githubusercontent.com/13689192/103189046-8332c380-48fd-11eb-9902-1e0bf9023fa3.png>
>
You want the uneditable input thing?

>
> <https://user-images.githubusercontent.com/13689192/103189046-8332c380-48fd-11eb-9902-1e0bf9023fa3.png>
>

2020-12-28 13:51 UTC, McSinyx commented
I'm not sure how I'm supposed to put it, don't you see how the

> student
>
> u/adaml

thing is giving confusion rather than information?  A readonly input would be fine, or anything that gives the information some context.

2020-12-28 14:09 UTC, Huy-Ngo commented
> don't you see how the
>
>>  student
>>    u/adaml
>
>thing is giving confusion rather than information?

No I don't. I believe anyone using this system has the ability to deduce from the context. Like on most social media they put `@username` or `u/username` (maybe even without any prefix) and anyone knows it's username without problem. You can put "software engineer" in your CV and the employer knows it's your expected position without further explanation. You also would write "John Doe, M.Sc" rather than "John Doe, Degree: Master of Science".

Those labels feel redundant and awkward.

2020-12-28 14:11 UTC, Huy-Ngo commented
Or maybe I should remove them for edit page; that would be better.

2020-12-28 14:12 UTC, McSinyx commented
> Those labels feel redundant and awkward.

If you insist :shrug:  BTW rmb to add the email to the public readonly page.

2020-12-28 14:20 UTC, Huy-Ngo commented
> rmb to add the email to the public readonly page

Wait I thought we shouldn't display email like it could lead to crawling for example.

2020-12-28 14:27 UTC, McSinyx commented
How else would one get the contact information (which I argue to be the only reason we have the user page at all)?  As for crawling we can add a [rate limiter](https://pypi.org/project/Quart-Rate-Limiter/).  Later (or now) we can add some sort of address obscurer which produces harder to detect strings like `mcsinyx (at) disroot (dot) org`.

2020-12-28 14:37 UTC, Huy-Ngo commented
Alright then. Since all these emails are fake anyway we can ignore that for now.

2020-12-28 14:56 UTC, McSinyx approved these changes
I don't see anything stopping this from getting merged at the moment.

2020-12-31 04:46 UTC, DDHLong approved these changes

2020-12-31 04:46 UTC, merged