Doubly link users and projects
Huy-Ngo/acanban pull request #87
Opened 2020-12-26 09:26 UTC by McSinyx

My attempt to resolve GH-71.

2020-12-26 13:18 UTC, Huy-Ngo requested changes

2020-12-26 13:18 UTC, Huy-Ngo commented on tests/assets/rethinkdump/test/users.json
> +    "projects": [],
I don't think assistants should have this field (project).

2020-12-26 16:14 UTC, McSinyx commented on tests/assets/rethinkdump/test/users.json
> +    "projects": [],
Thanks, addressed.

2020-12-27 15:05 UTC, Huy-Ngo approved these changes

2020-12-31 08:33 UTC, 9a24f0 approved these changes
LGTM

2020-12-31 08:34 UTC, merged