Define project's objective
Huy-Ngo/acanban pull request #89
Opened 2020-12-28 16:22 UTC by McSinyx

I should have written the introduction but my brain refuses to produce literature today.

Hopefully resolve GH-16 ([sorry 4 the wait](https://en.wikipedia.org/wiki/Sorry_4_the_Wait) though).

2020-12-29 15:02 UTC, Huy-Ngo commented
Can the user define their own Kanban columns? I thought we would allow that with the 3 columns as default.

2020-12-29 15:11 UTC, Huy-Ngo requested changes
There's a spelling mistake, as always.

2020-12-29 15:11 UTC, Huy-Ngo commented on docs/source/obj.rst
> +The Academic Itergration
```suggestion
The Academic Integration
```

2020-12-29 15:13 UTC, McSinyx commented on docs/source/obj.rst
> +The Academic Itergration
Huh I should use word completion for every word now :smile:

2020-12-29 15:21 UTC, Huy-Ngo commented on docs/source/obj.rst
> +The Academic Itergration
You can try something like `ispell` but it nitpicks valid words like "workflow" or "Kanban" or "http".

2020-12-29 15:21 UTC, Huy-Ngo approved these changes

2020-12-29 15:22 UTC, McSinyx commented on docs/source/obj.rst
> +The Academic Itergration
I can use the builtin spell, but never rmb to turn it on.  Maybe I should make it the default for markup languages :shrug:

2020-12-31 04:48 UTC, DDHLong approved these changes

2020-12-31 04:49 UTC, McSinyx commented
Thanks!

2020-12-31 04:49 UTC, merged