Split the document into multiple sections
Huy-Ngo/acanban pull request #99
Opened 2020-12-31 14:18 UTC by Huy-Ngo

Resolve #91

2020-12-31 14:21 UTC, McSinyx commented
For brievity, could you remove the subsubsections with just *None*?

2020-12-31 15:24 UTC, McSinyx requested changes

2020-12-31 15:24 UTC, McSinyx commented on docs/source/academic/index.rst
> +Academic Support
This standing alone as a chapter name does not sound right.

2020-12-31 15:24 UTC, McSinyx commented on docs/source/collab/index.rst
> +Collaboration
Same here.

2020-12-31 15:24 UTC, McSinyx commented on docs/source/webapp/index.rst
> +as the platform.
The title should reflect the *applicable* part.  The *be a web app* is already reasoned in the objective, it could be repeated but the emphasis should still be on making software that is portable and takes resource constraints into account.

Speaking of this, I forgot to mention about making it [free software](https://www.gnu.org/education/edu-schools.html).

2020-12-31 15:24 UTC, McSinyx commented on docs/source/webapp/index.rst
> +   suppl-spec
With the logic above, suppl-spec should be the requirement and thus be moved to the top.  The use cases doesn't seem to fit this chapter and can be move the the part about the generic colab platform.

2020-12-31 15:24 UTC, McSinyx commented on docs/source/index.rst
> +   arch/deploy
This is part of the solution for the applicable software.

2020-12-31 15:24 UTC, McSinyx commented on docs/source/index.rst
>     design/index
This should be split accordingly into collab and academic.

2020-12-31 15:44 UTC, Huy-Ngo commented on docs/source/webapp/index.rst
> +as the platform.
> forgot to mention about making it free software.

Where do you want to mention it, or should it be left for another issue?

2020-12-31 15:45 UTC, Huy-Ngo commented on docs/source/collab/index.rst
> +Collaboration
Maybe "Academic Evaluation" and "Collaboration Platform"?

2020-12-31 15:45 UTC, McSinyx commented on docs/source/webapp/index.rst
> +as the platform.
In the objective, and yes it's out-of-scope of this PR.

2020-12-31 15:46 UTC, Huy-Ngo commented on docs/source/webapp/index.rst
> +   suppl-spec
I thought you said these miscellaneous would be separated from the collab :( 

Maybe I'll move these use cases to "Other functionalities" or something?

2020-12-31 15:47 UTC, McSinyx commented on docs/source/collab/index.rst
> +Collaboration
Those still do not speak up the context, i.e. when put in parallel with *Introduction* and *Objective*.  Just use more words and I believe you can come up with something.

2020-12-31 15:47 UTC, Huy-Ngo commented on docs/source/index.rst
>     design/index
By "This" you mean `design/index`?

2020-12-31 15:50 UTC, McSinyx commented on docs/source/webapp/index.rst
> +   suppl-spec
For now, probably, we'll need to write the content to see if it fits in anywhere.

2020-12-31 15:51 UTC, McSinyx commented on docs/source/index.rst
>     design/index
Yep, sorry :sweat_smile:

2021-01-01 13:11 UTC, Huy-Ngo commented on docs/source/index.rst
>     design/index
I realized the database tables here are all used for collab :p

2021-01-01 13:15 UTC, Huy-Ngo commented on docs/source/collab/index.rst
> +Collaboration
> put in parallel with Introduction and Objective

Maybe those shouldn't go in parallel at the first place? We can have *Analysis and Design* chapter containing these 3 subsections.

2021-01-01 13:25 UTC, McSinyx commented on docs/source/collab/index.rst
> +Collaboration
*Did you mean Requirements, Analysis and Design?*

2021-01-03 04:02 UTC, McSinyx commented on docs/source/index.rst
> +   arch/deploy
Reading the commit messages, isn't arch/deploy supposed to be inside webapp?  BTW for the ease of review please rebase this on top of current main.

2021-01-03 04:29 UTC, Huy-Ngo commented on docs/source/index.rst
> +   arch/deploy
Sorry I forgot to remove that.

2021-01-03 04:37 UTC, McSinyx commented on docs/source/index.rst
> +   arch/deploy
Something doesn't seem right with the branch history, maybe another `git pull --rebase origin main`?

2021-01-03 04:39 UTC, Huy-Ngo commented
Hmm why does it contains these commits from master :confused:

2021-01-03 04:44 UTC, Huy-Ngo commented
I think it's fixed now.

On Sun, Jan 3, 2021 at 11:37 AM Nguyễn Gia Phong <notifications@github.com>
wrote:

> *@McSinyx* commented on this pull request.
> ------------------------------
>
> In docs/source/index.rst
> <https://github.com/Huy-Ngo/acanban/pull/99#discussion_r550955171>:
>
> > +   webapp/index
> +   arch/deploy
>
> Something doesn't seem right with the branch history, maybe another git
> pull --rebase origin main?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Huy-Ngo/acanban/pull/99#discussion_r550955171>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AETHFHTGFPAVLNYDLM47APDSX7YA5ANCNFSM4VPOSF6Q>
> .
>

2021-01-03 04:47 UTC, McSinyx approved these changes
[Looking good!](https://patchouli.sr.ht/builds.sr.ht/artifacts/~huyngo/384750/7211c77f14e2c5d2/acanban.pdf)

2021-01-03 15:10 UTC, 9a24f0 approved these changes
Looks good. But I'm wondering if we split in the actual report.

2021-01-03 15:12 UTC, McSinyx commented
This is the actual report, and splitting here can be think of as transposing the representation order.

2021-01-03 15:12 UTC, Huy-Ngo commented
Thanks

> Looks good. But I'm wondering if we split in the actual report.

You can download the [artifact](https://patchouli.sr.ht/builds.sr.ht/artifacts/~huyngo/384750/7211c77f14e2c5d2/acanban.pdf). Btw source hut artifact is so much better than GitHub's.

2021-01-03 15:13 UTC, merged